Force targetRevision to be always a string
Jonny had a branch called '410' and the installation broke like this:

    $ make install
    make -f common/Makefile operator-deploy
    make[1]: Entering directory '/home/michele/Engineering/cloud-patterns/multicloud-gitops'
    Checking repo https://github.com/mbaldessari/multicloud-gitops.git - branch 410
    https://github.com/mbaldessari/multicloud-gitops.git - 410 exists
    helm upgrade --install multicloud-gitops common/operator-install/ -f values-global.yaml --set main.git.repoURL="https://github.com/mbaldessari/multicloud-gitops.git" --set main.git.revision=410 --set global.hubClusterDomain=apps.mcg-hub.blueprints.rhecoeng.com
    Release "multicloud-gitops" does not exist. Installing it now.
    Error: Pattern.gitops.hybrid-cloud-patterns.io "multicloud-gitops" is invalid: spec.gitSpec.targetRevision: Invalid value: "integer": spec.gitSpec.targetRevision in body must be of type string: "integer"
    make[1]: *** [common/Makefile:70: operator-deploy] Error 1
    make[1]: Leaving directory '/home/michele/Engineering/cloud-patterns/multicloud-gitops'
    make: *** [Makefile:10: operator-deploy] Error 2

Make sure we always quote the targetRevision.
Tested and it fixed the deployment with a numeric-only branch